- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "target/internal2-1.0-SNAPSHOT.war"
        dest: "/opt/tomcat/webapps/internal2.war"

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
